version: '3.8'

services:
    zookeeper:
      image: confluentinc/cp-zookeeper:7.2.1
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "2181:2181"

    kafka:
      image: confluentinc/cp-kafka:7.2.1
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - ./mongo-data:/data/db

    producer:
      build: ./producer
      container_name: producer
      depends_on:
        - kafka
        - mongodb
      ports:
        - "8080:8080"

    consumer:
      build: ./consumer
      container_name: consumer
      depends_on:
        - kafka
        - mongodb
      ports:
        - "8081:8081"